- name: install required base packages
  dnf: name={{item}} state=latest
  with_items:
    - bison
    - cpp
    - cmake
    - elfutils-libelf-devel
    - ethtool
    - flex
    - gcc
    - gcc-c++
    - git
    - iperf
    - kernel-devel
    - kernel-headers
    - libstdc++-static
    - luajit
    - luajit-devel
    - clang
    - clang-devel
    - clang-libs
    - lldb
    - lldb-devel
    - llvm
    - llvm-devel
    - llvm-libs
    - make
    - perl
    - unzip
    - python-netaddr
    - python-pip
    - zlib-devel

