- name: fedora base box config
  hosts: all
  vars:
    syslog_remote: ninja
    syslog_remote_port: 5140
    audit_syslog_active: yes
    audit_write_local: no
    audit_log_format: ENRICHED
    audit_dispatch_q_depth: 20000
  tasks:
    - include: task_test_environment.yml
    - include: fedora_task_repos.yml
    - include: fedora_task_packages.yml
