- name: fedora base box config
  hosts: all
  vars:
    syslog_remote: ninja
    syslog_remote_port: 5140
    audit_syslog_active: yes
    audit_write_local: no
    audit_log_format: ENRICHED
    audit_dispatch_q_depth: 20000
