- name: configure rsyslog destination
  template: src=templates/rsyslog-remote.conf.j2 dest=/etc/rsyslog.d/99-rsyslog-remote.conf mode=0644 owner=root group=root
  when: hvm_aws is defined and hvm_aws==False
- name: enable ntpd
  systemd: service=ntpd state=started enabled=yes
