- name: install repo key
  command: rpm --import http://yum-repo-ryanbreed.s3-website-us-west-2.amazonaws.com/RPM-GPG-KEY-yum-repo-ryanbreed
- name: install epel
  yum: name=epel-release state=installed
- name: enable extras repo
  command: yum-config-manager --save --setopt=extras.enabled=1
